import assert from "node:assert/strict";
import crypto from "node:crypto";
import fs from "node:fs";
import test from "node:test";
import {aboutSectionCopy,getAboutSectionIds,isAboutSection} from "../../src/lib/about";
import {localizedPath,resolveEnglishSegments} from "../../src/lib/i18n/routing";
const ids=["profile","calling","education-ministry","writing-preaching","publishing-media","contact","support"];
const hash=(p:string)=>crypto.createHash("sha256").update(fs.readFileSync(p)).digest("hex");
test("About has exactly seven permanent sections in canonical order",()=>{assert.deepEqual(getAboutSectionIds(),ids);assert.deepEqual(ids.map(id=>aboutSectionCopy("zh-CN",id as never).label),["个人简介","我的呼召","教育与服事","写作与讲道","出版与媒体","联系方式","支持这份工作"]);assert.deepEqual(ids.map(id=>aboutSectionCopy("en-US",id as never).label),["Profile","Calling","Education & Ministry","Writing & Preaching","Publishing & Media","Contact","Support This Work"]);});
test("About resolver accepts only permanent identities",()=>{for(const id of ids)assert.equal(isAboutSection(id),true);for(const old of ["paul","story","ministry","education","beliefs","projects"])assert.equal(isAboutSection(old),false);});
test("canonical Contact and Support routes remain bilingual under About",()=>{assert.equal(localizedPath("contact","zh-CN"),"/about/contact");assert.equal(localizedPath("contact","en-US"),"/en/about/contact");assert.equal(localizedPath("support","zh-CN"),"/about/support");assert.equal(localizedPath("support","en-US"),"/en/about/support");assert.equal(resolveEnglishSegments(["about","contact"]),"contact");assert.equal(resolveEnglishSegments(["about","support"]),"support");});
test("approved Contact and Support substantive implementations remain byte-identical to main",()=>{assert.equal(hash("src/components/product/social-contact-page.tsx"),"f4aa9d48984227a3bd292462b336f0bc2ced40e79582672249da6ef784cb9fbe");assert.equal(hash("src/components/product/support-page.tsx"),"37254b08bd57f98ab55bff29cbec10313aefadcf6a930a39e3a6335501b21888");assert.equal(hash("src/data/support-methods.ts"),"1d7dcd37fc9a2b58e0ab494d2e57a3d413763b6b35fe94bf563f6ceb00d8b7ff");});
test("About landing is production content with responsive permanent cards",()=>{const page=fs.readFileSync("src/components/content/about-page.tsx","utf8");assert.match(page,/认识 Paul，以及这个网站背后的生命、呼召与使命。/);assert.match(page,/更多关于我 →/);assert.match(page,/认识 Paul/);assert.match(page,/sm:grid-cols-2 lg:grid-cols-3/);assert.match(page,/lg:grid-cols-\[17rem_minmax\(0,1fr\)\]/);assert.doesNotMatch(page,/V1 Runtime Foundation|正式内容将在后续任务中加入/);});
