import assert from "node:assert/strict";
import fs from "node:fs";
import test from "node:test";
import {ANALYTICS_CONSENT_STORAGE_KEY,GA4_MEASUREMENT_ID} from "../../src/components/analytics/google-analytics-consent";

test("GA4 uses the owner-provided measurement ID and versioned scoped consent",()=>{assert.equal(GA4_MEASUREMENT_ID,"G-YC5TTPM9GE");assert.equal(ANALYTICS_CONSENT_STORAGE_KEY,"paulzhang.analytics-consent.v1");});
test("GA4 is installed once in the shared bilingual root and only rendered after granted consent",()=>{const layout=fs.readFileSync("src/components/layout/locale-root-layout.tsx","utf8");const component=fs.readFileSync("src/components/analytics/google-analytics-consent.tsx","utf8");assert.equal((layout.match(/<GoogleAnalyticsConsent/g)||[]).length,1);assert.match(component,/consent==="granted"/);assert.match(component,/googletagmanager\.com\/gtag\/js/);assert.match(component,/gtag\('config','\$\{GA4_MEASUREMENT_ID\}'\)/);assert.doesNotMatch(layout,/G-YC5TTPM9GE/);});
test("consent UI is bilingual and supports grant, deny, and later changes",()=>{const component=fs.readFileSync("src/components/analytics/google-analytics-consent.tsx","utf8");for(const text of ["允许分析","不允许","分析设置","Allow analytics","Do not allow","Analytics settings"])assert.match(component,new RegExp(text));assert.match(component,/localStorage\.setItem/);});
test("CSP permits only required Google tag and collection origins while preserving Together",()=>{const headers=fs.readFileSync("public/_headers","utf8");assert.match(headers,/script-src[^\n]*https:\/\/www\.googletagmanager\.com/);assert.match(headers,/connect-src[^\n]*https:\/\/www\.google-analytics\.com/);assert.match(headers,/connect-src[^\n]*https:\/\/\*\.google-analytics\.com/);assert.match(headers,/paulzhang-together\.paulzhang901\.workers\.dev/);});
test("privacy contract explicitly keeps raw sensitive content out of GA4",()=>{const adr=fs.readFileSync("docs/adr/0027-consent-gated-ga4-analytics.md","utf8");assert.match(adr,/MUST NOT load before/);assert.match(adr,/MUST NOT send prayer text, form values, search text/);assert.match(adr,/Cloudflare Web Analytics remains independent and unchanged/);});
