import Link from "next/link";
import type {Route} from "next";
import type {ReactNode} from "react";
import {Container,ReadingContainer} from "@/components/layout/container";
import {Section,SectionHeading} from "@/components/layout/section";
import {aboutSectionCopy,getAboutSectionIds,type AboutSectionId} from "@/lib/about";
import {getAboutBiography} from "@/lib/about-biography";
import {aboutWritingEssayPath,getAboutWritingEssay} from "@/lib/about-writing-essays";
import {getContentRepository} from "@/lib/content/repository";
import {PublishingMediaPage} from "@/components/content/publishing-media-page";
import type {Locale} from "@/config/i18n";

const prefix=(locale:Locale)=>locale==="en-US"?"/en":"";
export const aboutHref=(locale:Locale,id:AboutSectionId)=>`${prefix(locale)}/about/${id}` as Route;
export function AboutNav({locale,current}:{locale:Locale;current?:AboutSectionId}){return <aside><Link href={`${prefix(locale)}/about` as Route} className="font-serif text-2xl hover:underline">{locale==="zh-CN"?"关于":"About"}</Link><nav aria-label={locale==="zh-CN"?"关于栏目":"About sections"} className="mt-6 flex flex-wrap gap-2 lg:flex-col lg:items-start">{getAboutSectionIds().map(id=><Link key={id} href={aboutHref(locale,id)} aria-current={id===current?"page":undefined} className="rounded-full border bg-surface px-4 py-2 text-sm hover:bg-muted lg:w-full lg:rounded-md">{aboutSectionCopy(locale,id).label}</Link>)}</nav></aside>}
function Cards({locale}:{locale:Locale}){return <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{getAboutSectionIds().map((id,index)=>{const item=aboutSectionCopy(locale,id);return <Link key={id} href={aboutHref(locale,id)} className="group rounded-xl border bg-surface p-6 transition hover:-translate-y-0.5 hover:border-primary/50 hover:shadow-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary"><span className="text-sm font-semibold text-primary">{String(index+1).padStart(2,"0")}</span><h3 className="mt-3 font-serif text-2xl leading-tight group-hover:underline">{item.label}</h3><p className="mt-3 leading-7 text-muted-foreground">{item.summary}</p><span className="mt-5 inline-block font-medium text-primary" aria-hidden="true">→</span></Link>})}</div>}
export function AboutPage({locale}:{locale:Locale}){return <><Section className="border-b bg-muted/40"><Container><ReadingContainer className="px-0"><SectionHeading eyebrow={locale==="zh-CN"?"关于 · ABOUT":"ABOUT"} title={locale==="zh-CN"?"关于":"About"}><p>{locale==="zh-CN"?"认识 Paul，以及这个网站背后的生命、呼召与使命。":"Meet Paul and the life, calling, and mission behind this website."}</p></SectionHeading><Link href={aboutHref(locale,"profile")} className="inline-flex min-h-11 items-center rounded-md bg-primary px-5 font-medium text-primary-foreground">{locale==="zh-CN"?"更多关于我 →":"More About Me →"}</Link></ReadingContainer></Container></Section><Section><Container><div className="mb-8 max-w-2xl"><h2 className="font-serif text-3xl sm:text-4xl">{locale==="zh-CN"?"认识 Paul":"Meet Paul"}</h2></div><Cards locale={locale}/></Container></Section></>}
export async function AboutSectionPage({locale,section}:{locale:Locale;section:Exclude<AboutSectionId,"contact"|"support">}){const item=aboutSectionCopy(locale,section);const biography=getAboutBiography(locale,section);const coreEssay=section==="writing-preaching"?getAboutWritingEssay(await getContentRepository(),locale,"speak-write-live-the-word"):null;return <Section><Container><div className="grid gap-10 lg:grid-cols-[17rem_minmax(0,1fr)]"><AboutNav locale={locale} current={section}/><article className="min-w-0"><p className="text-sm font-semibold uppercase tracking-[0.14em] text-primary">{locale==="zh-CN"?"关于":"About"}</p><h1 className="mt-3 font-serif text-4xl leading-tight sm:text-5xl">{item.label}</h1>{section==="publishing-media"?<PublishingMediaPage locale={locale}/>:biography?<>{(biography.intro??biography.subtitle)&&<p className="mt-6 max-w-2xl text-lg leading-8 text-muted-foreground">{biography.intro??biography.subtitle}</p>}<div className="prose-content mt-10 max-w-[var(--container-reading)]">{biography.paragraphs.map((part,index)=>Array.isArray(part)?<blockquote key={index}>{part.map(line=><p key={line}>{line}</p>)}</blockquote>:<p key={index}>{part}</p>)}</div>{coreEssay?<aside className="mt-12 max-w-[var(--container-reading)] border-t pt-8"><h2 className="font-serif text-2xl">{locale==="zh-CN"?"核心理念文章":"Core Philosophy Essay"}</h2><Link href={aboutWritingEssayPath(locale,"speak-write-live-the-word")} className="group mt-5 block rounded-xl border bg-surface p-6 transition hover:border-primary/50 hover:shadow-sm"><h3 className="font-serif text-2xl leading-tight group-hover:underline">{coreEssay.title}</h3>{coreEssay.subtitle?<p className="mt-3 leading-7 text-muted-foreground">{coreEssay.subtitle}</p>:null}<span className="mt-5 inline-block font-medium text-primary" aria-hidden="true">→</span></Link></aside>:null}</>:<p className="mt-6 max-w-2xl text-lg leading-8 text-muted-foreground">{item.summary}</p>}</article></div></Container></Section>}
export function AboutIntegratedPage({locale,section,children}:{locale:Locale;section:"contact"|"support";children:ReactNode}){return <Section className="py-0"><Container><div className="grid gap-10 lg:grid-cols-[17rem_minmax(0,1fr)]"><div className="py-[var(--space-section)]"><AboutNav locale={locale} current={section}/></div><div className="min-w-0">{children}</div></div></Container></Section>}
