import Link from "next/link";
import type {Route} from "next";
import {Container,ReadingContainer} from "@/components/layout/container";
import {Section,SectionHeading} from "@/components/layout/section";
import {communitySectionCopy,getCommunitySectionIds,type CommunitySectionId} from "@/lib/community";
import {ChurchIntroductionPage} from "@/components/content/church-introduction-page";
import {SundayWorshipPage} from "@/components/content/sunday-worship-page";
import type {ContentLanguage} from "@/types/content";

const prefix=(locale:ContentLanguage)=>locale==="en-US"?"/en":"";
const href=(locale:ContentLanguage,id:CommunitySectionId)=>`${prefix(locale)}/community/${id}` as Route;
function CommunityNav({locale}:{locale:ContentLanguage}){return <nav aria-label={locale==="zh-CN"?"群体栏目":"Community sections"} className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{getCommunitySectionIds().map((id,index)=>{const item=communitySectionCopy(locale,id);return <Link key={id} href={href(locale,id)} className="group rounded-xl border bg-surface p-6 transition hover:-translate-y-0.5 hover:border-primary/50 hover:shadow-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary"><span className="text-sm font-semibold text-primary">{String(index+1).padStart(2,"0")}</span><h2 className="mt-3 font-serif text-2xl leading-tight group-hover:underline">{item.label}</h2><p className="mt-3 leading-7 text-muted-foreground">{item.summary}</p><span className="mt-5 inline-block font-medium text-primary" aria-hidden="true">→</span></Link>})}</nav>}
export function CommunityPage({locale}:{locale:ContentLanguage}){return <><Section className="border-b bg-muted/40"><Container><ReadingContainer className="px-0"><SectionHeading eyebrow={locale==="zh-CN"?"群体 · Community":"Community"} title={locale==="zh-CN"?"群体":"Community"}><p>{locale==="zh-CN"?"在真实的群体中一起成长、彼此建立。":"Growing together and building one another up in real community."}</p></SectionHeading><Link href={href(locale,"church")} className="inline-flex min-h-11 items-center rounded-md bg-primary px-5 font-medium text-primary-foreground">{locale==="zh-CN"?"了解我们的群体 →":"Discover Our Community →"}</Link></ReadingContainer></Container></Section><Section><Container><div className="mb-8 max-w-2xl"><p className="text-sm font-semibold uppercase tracking-[0.14em] text-primary">{locale==="zh-CN"?"一起生活 · 一起成长":"Belong · Grow · Serve"}</p><h2 className="mt-3 font-serif text-3xl sm:text-4xl">{locale==="zh-CN"?"找到你进入群体的下一步":"Find your next step into community"}</h2></div><CommunityNav locale={locale}/></Container></Section></>}
export function CommunitySectionPage({locale,section}:{locale:ContentLanguage;section:CommunitySectionId}){const item=communitySectionCopy(locale,section);return <Section><Container><div className="grid gap-10 lg:grid-cols-[17rem_minmax(0,1fr)]"><aside><Link href={`${prefix(locale)}/community` as Route} className="font-serif text-2xl hover:underline">{locale==="zh-CN"?"群体":"Community"}</Link><nav aria-label={locale==="zh-CN"?"群体栏目":"Community sections"} className="mt-6 flex flex-wrap gap-2 lg:flex-col lg:items-start">{getCommunitySectionIds().map(id=><Link key={id} href={href(locale,id)} aria-current={id===section?"page":undefined} className="rounded-full border bg-surface px-4 py-2 text-sm hover:bg-muted lg:w-full lg:rounded-md">{communitySectionCopy(locale,id).label}</Link>)}</nav></aside><article>{section==="church"?<ChurchIntroductionPage locale={locale}/>:section==="sunday"?<SundayWorshipPage locale={locale}/>:<><p className="text-sm font-semibold uppercase tracking-[0.14em] text-primary">{locale==="zh-CN"?"群体":"Community"}</p><h1 className="mt-3 font-serif text-4xl leading-tight sm:text-5xl">{item.label}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-muted-foreground">{item.summary}</p></>}</article></div></Container></Section>}
