import Link from "next/link";
import type {Route} from "next";
import {Container, ReadingContainer} from "@/components/layout/container";
import {Section, SectionHeading} from "@/components/layout/section";
import {contentPath} from "@/lib/content/paths";
import type {ContentRepository} from "@/lib/content/repository";
import {getGrowthStageIds, getGrowthStageItems, growthStageLabel} from "@/lib/content/growth";
import type {ContentLanguage} from "@/types/content";

const prefix=(locale:ContentLanguage)=>locale === "en-US" ? "/en" : "";
function StageNav({locale}:{locale:ContentLanguage}) { return <aside aria-labelledby="growth-stages"><h2 id="growth-stages" className="font-serif text-2xl">{locale === "zh-CN" ? "按成长阶段开始" : "Explore by Stage"}</h2><p className="mt-3 leading-7 text-muted-foreground">{locale === "zh-CN" ? "选择一个阶段，进入相应的真理、操练与生命成长内容。" : "Choose a stage for truth, practice, and formation resources suited to that step."}</p><nav aria-label={locale === "zh-CN" ? "成长阶段" : "Growth stages"} className="mt-6 flex flex-wrap gap-2 lg:flex-col lg:items-start">{getGrowthStageIds().map(stage=><Link key={stage} href={`${prefix(locale)}/grow/${stage}` as Route} className="rounded-full border bg-surface px-4 py-2 text-sm hover:bg-muted lg:w-full lg:rounded-md">{growthStageLabel(locale,stage)}</Link>)}</nav></aside>; }
function Results({locale,stage,repository}:{locale:ContentLanguage;stage:string;repository:ContentRepository}) { const items=getGrowthStageItems(repository,locale,stage); return <div><h2 className="font-serif text-3xl">{growthStageLabel(locale,stage)}</h2><p className="mt-3 text-muted-foreground">{locale === "zh-CN" ? "这个阶段的成长内容" : "Resources for this stage of growth"}</p><div className="mt-8 space-y-6">{items.length ? items.map(item=><article key={item.id} className="border-y py-6"><h3 className="font-serif text-2xl"><Link className="hover:underline" href={contentPath(item)}>{item.title}</Link></h3><p className="mt-3 leading-7 text-muted-foreground">{item.summary}</p></article>) : <p className="rounded-lg border border-dashed p-8 text-muted-foreground">{locale === "zh-CN" ? "这个阶段目前还没有已公开的内容。" : "No published resources are available for this stage yet."}</p>}</div></div>; }
export function GrowthPage({locale,repository}:{locale:ContentLanguage;repository:ContentRepository}) { return <><Section className="border-b bg-muted/40"><Container><ReadingContainer className="px-0"><SectionHeading eyebrow={locale === "zh-CN" ? "生命成长" : "Spiritual Formation"} title={locale === "zh-CN" ? "成长路径" : "Growth Pathways"}><p>{locale === "zh-CN" ? "从探索基督到为基督倍增，在每一个阶段持续认识、跟随并活出基督。" : "From exploring Christ to multiplying for Christ, keep knowing, following, and living in Christ at every stage."}</p></SectionHeading></ReadingContainer></Container></Section><Section><Container><div className="grid gap-10 lg:grid-cols-[17rem_minmax(0,1fr)]"><StageNav locale={locale}/><Results locale={locale} stage="explore" repository={repository}/></div></Container></Section></>; }
export function GrowthStagePage({locale,stage,repository}:{locale:ContentLanguage;stage:string;repository:ContentRepository}) { return <Section><Container><div className="grid gap-10 lg:grid-cols-[17rem_minmax(0,1fr)]"><StageNav locale={locale}/><Results locale={locale} stage={stage} repository={repository}/></div></Container></Section>; }
