import Link from "next/link";
import type {Route} from "next";
import {Container,ReadingContainer} from "@/components/layout/container";
import {Section,SectionHeading} from "@/components/layout/section";
import {getLightJourneySectionIds,lightJourneySectionCopy,type LightJourneySectionId} from "@/lib/light-journey";
import type {Locale} from "@/config/i18n";
const prefix=(locale:Locale)=>locale==="en-US"?"/en":"";
const href=(locale:Locale,id:LightJourneySectionId)=>`${prefix(locale)}/journey/${id}` as Route;
function Cards({locale}:{locale:Locale}){return <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{getLightJourneySectionIds().map((id,index)=>{const item=lightJourneySectionCopy(locale,id);return <Link key={id} href={href(locale,id)} className="group rounded-xl border bg-surface p-6 transition hover:-translate-y-0.5 hover:border-primary/50 hover:shadow-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary"><span className="text-sm font-semibold text-primary">{String(index+1).padStart(2,"0")}</span><h2 className="mt-3 font-serif text-2xl leading-tight group-hover:underline">{item.label}</h2><p className="mt-3 leading-7 text-muted-foreground">{item.summary}</p><span className="mt-5 inline-block font-medium text-primary" aria-hidden="true">→</span></Link>})}</div>}
export function LightJourneyPage({locale}:{locale:Locale}){return <><Section className="border-b bg-muted/40"><Container><ReadingContainer className="px-0"><SectionHeading eyebrow={locale==="zh-CN"?"光旅 · LIGHT JOURNEY":"LIGHT JOURNEY"} title={locale==="zh-CN"?"光旅":"Light Journey"}><p>{locale==="zh-CN"?"在旅途中看见世界，也看见神的作为。":"Seeing the world along the journey, and seeing God's work within it."}</p></SectionHeading></ReadingContainer></Container></Section><Section><Container><Cards locale={locale}/></Container></Section></>}
export function LightJourneySectionPage({locale,section}:{locale:Locale;section:LightJourneySectionId}){const item=lightJourneySectionCopy(locale,section);return <Section><Container><div className="grid gap-10 lg:grid-cols-[17rem_minmax(0,1fr)]"><aside><Link href={`${prefix(locale)}/journey` as Route} className="font-serif text-2xl hover:underline">{locale==="zh-CN"?"光旅":"Light Journey"}</Link><nav aria-label={locale==="zh-CN"?"光旅栏目":"Light Journey sections"} className="mt-6 flex flex-wrap gap-2 lg:flex-col lg:items-start">{getLightJourneySectionIds().map(id=><Link key={id} href={href(locale,id)} aria-current={id===section?"page":undefined} className="rounded-full border bg-surface px-4 py-2 text-sm hover:bg-muted lg:w-full lg:rounded-md">{lightJourneySectionCopy(locale,id).label}</Link>)}</nav></aside><article><p className="text-sm font-semibold uppercase tracking-[0.14em] text-primary">{locale==="zh-CN"?"光旅":"Light Journey"}</p><h1 className="mt-3 font-serif text-4xl leading-tight sm:text-5xl">{item.label}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-muted-foreground">{item.summary}</p></article></div></Container></Section>}
