import Link from "next/link";
import type {Route} from "next";
import {currentSunday,sundayStableData} from "@/data/sunday";
import type {ContentLanguage} from "@/types/content";
const prefix=(locale:ContentLanguage)=>locale==="zh-CN"?"":`/en`;
const copy={"zh-CN":{eyebrow:"印城第一华人循理会 · FCFMC",title:"主日敬拜",welcome:"欢迎你和家人一起来敬拜。无论你已经信主多年，正在认识基督信仰，还是第一次来到教会，我们都欢迎你。",locationTitle:"我们现在在哪里",locationBody:"我们目前没有自己的教堂建筑，在这个过渡时期借用其他教会群体的场地举行主日敬拜和相关聚会。我们感谢神的预备，也继续祷告寻找适合教会长期发展的永久场所。",thisSunday:"本周主日",scripture:"经文",speaker:"讲员",points:"讲道大纲",watch:"观看主日信息",read:"阅读讲章",expect:"主日敬拜流程",gatherings:"每周聚会",locationDetails:"联系我们了解地点",onlineTitle:"线上参加晨灵修？",onlineBody:"请联系我们获取 Zoom 信息。",visit:"第一次来？",visitTime:"主日时间",visitAddress:"地址",visitBody:"第一次来不需要特别准备，也不需要提前报名。欢迎你直接来到我们的主日敬拜。到达以后，会有弟兄姊妹接待你。",language:"我们的主日敬拜主要服事华人及华语家庭，敬拜材料中也使用中英文内容。",online:"教会在线入口",website:"教会官网",youtube:"教会 YouTube",visitOnline:"访问",next:"继续认识 FCFMC",church:"认识我们的教会",groups:"小组与团契",choir:"诗班与服事",youth:"青年与下一代",care:"社区关怀",contact:"联系我们"},
"en-US":{eyebrow:"The First Chinese Free Methodist Church of Indianapolis · FCFMC",title:"Sunday Worship",welcome:"You and your family are welcome to worship with us. Whether you have followed Christ for many years, are exploring the Christian faith, or are visiting a church for the first time, you are welcome here.",locationTitle:"Where We Gather Today",locationBody:"We currently do not own a church building. During this season of transition, we gather for Sunday worship and other ministries in space shared with us by another church community. We are grateful for God’s provision as we continue to pray and search for a permanent home for the congregation.",thisSunday:"This Sunday",scripture:"Scripture",speaker:"Speaker",points:"Sermon Outline",watch:"Watch the Sermon",read:"Read the Sermon",expect:"What to Expect",gatherings:"Weekly Gatherings",locationDetails:"Contact us for location details",onlineTitle:"Joining Morning Devotion online?",onlineBody:"Contact us for Zoom details.",visit:"Plan Your Visit",visitTime:"Sunday time",visitAddress:"Address",visitBody:"No advance registration is required. You are welcome to simply join us for Sunday worship. When you arrive, members of our congregation will be glad to welcome you.",language:"Our Sunday worship primarily serves Chinese-speaking individuals and families, with both Chinese and English appearing in portions of our worship materials.",online:"Church Online",website:"Church Website",youtube:"Church YouTube",visitOnline:"Visit",next:"Continue Exploring FCFMC",church:"Meet Our Church",groups:"Groups & Fellowship",choir:"Choir & Serving",youth:"Youth & Next Generation",care:"Community Care",contact:"Contact Us"}} as const;
export function SundayWorshipPage({locale}:{locale:ContentLanguage}){const c=copy[locale],zh=locale==="zh-CN",s=sundayStableData,w=currentSunday;const internal=[["church",c.church],["groups",c.groups],["choir",c.choir],["youth",c.youth],["care",c.care]] as const;return <article className="max-w-5xl">
<header><p className="text-sm font-semibold uppercase tracking-[0.14em] text-primary">{c.eyebrow}</p><h1 className="mt-3 font-serif text-4xl leading-tight sm:text-5xl">{c.title}</h1><div className="mt-7 grid gap-4 sm:grid-cols-2"><InfoCard label={zh?s.worship.dayZh:s.worship.dayEn} value={s.worship.time}/><InfoCard label={zh?"聚会地点":"Gathering Location"} value={`${s.church.gatheringLocation.street}\n${s.church.gatheringLocation.cityRegionPostal}`}/></div><p className="mt-7 max-w-3xl text-lg leading-8 text-muted-foreground">{c.welcome}</p></header>
<section className="mt-12 border-t pt-10"><h2 className="font-serif text-3xl">{c.locationTitle}</h2><p className="mt-4 max-w-3xl leading-8 text-muted-foreground">{c.locationBody}</p></section>
<section className="mt-12 rounded-xl border bg-surface p-6 shadow-[var(--shadow-soft)] sm:p-8"><p className="text-sm font-semibold uppercase tracking-[0.14em] text-primary">{w.date}</p><h2 className="mt-2 font-serif text-3xl">{c.thisSunday}</h2><h3 className="mt-6 font-serif text-3xl sm:text-4xl">{zh?w.sermonTitleZh:w.sermonTitleEn}</h3><dl className="mt-6 grid gap-4 sm:grid-cols-2"><Fact term={c.scripture} value={zh?w.scriptureZh:w.scriptureEn}/><Fact term={c.speaker} value={zh?w.speakerZh:w.speakerEn}/></dl><h4 className="mt-8 font-semibold">{c.points}</h4><ol className="mt-4 grid gap-3">{w.sermonPoints.map((p,i)=><li key={p.en} className="rounded-lg border p-4"><span className="mr-3 font-semibold text-primary">{i+1}.</span>{zh?p.zh:p.en}</li>)}</ol>{w.youtubeUrl||w.sermonUrl?<div className="mt-6 flex flex-wrap gap-3">{w.youtubeUrl?<ExternalButton href={w.youtubeUrl} label={c.watch}/>:null}{w.sermonUrl?<LinkButton href={w.sermonUrl} label={c.read}/>:null}</div>:null}</section>
<section className="mt-12 border-t pt-10"><h2 className="font-serif text-3xl">{c.expect}</h2><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{s.order.map(item=><div key={item.en} className="rounded-lg border bg-surface p-4">{zh?item.zh:item.en}</div>)}</div></section>
<section className="mt-12 border-t pt-10"><h2 className="font-serif text-3xl">{c.gatherings}</h2><div className="mt-6 grid gap-4 sm:grid-cols-2">{s.gatherings.map(item=><article key={item.en} className="rounded-lg border bg-surface p-5"><h3 className="font-serif text-xl">{zh?item.zh:item.en}</h3><p className="mt-2 font-medium">{zh?item.dayZh:item.dayEn} · {item.time}</p>{"contactForLocation" in item&&item.contactForLocation?<Link href={`${prefix(locale)}/about/contact` as Route} className="mt-3 inline-block text-sm font-medium text-primary hover:underline">{c.locationDetails} →</Link>:null}{"online" in item&&item.online?<div className="mt-4 border-t pt-4"><p className="font-medium">{c.onlineTitle}</p><Link href={`${prefix(locale)}/about/contact` as Route} className="mt-1 inline-block text-sm text-primary hover:underline">{c.onlineBody} →</Link></div>:null}</article>)}</div></section>
<section className="mt-12 border-t pt-10"><h2 className="font-serif text-3xl">{c.visit}</h2><div className="mt-6 grid gap-4 sm:grid-cols-2"><InfoCard label={c.visitTime} value={s.worship.time}/><InfoCard label={c.visitAddress} value={`${s.church.gatheringLocation.street}\n${s.church.gatheringLocation.cityRegionPostal}`}/></div><p className="mt-6 max-w-3xl leading-8 text-muted-foreground">{c.visitBody}</p><p className="mt-4 max-w-3xl leading-8 text-muted-foreground">{c.language}</p></section>
<section className="mt-12 border-t pt-10"><h2 className="font-serif text-3xl">{c.online}</h2><div className="mt-6 grid gap-4 sm:grid-cols-2"><ExternalCard title={c.website} detail="fcfmchurch.org" href={s.church.website.url} action={c.visitOnline}/><ExternalCard title={c.youtube} detail={s.church.youtube.handle} href={s.church.youtube.url} action={c.visitOnline}/></div></section>
<nav aria-label={c.next} className="mt-12 border-t pt-8"><h2 className="font-serif text-2xl">{c.next}</h2><div className="mt-5 flex flex-wrap gap-3">{internal.map(([slug,label])=><LinkButton key={slug} href={`${prefix(locale)}/community/${slug}`} label={label}/>)}<LinkButton href={`${prefix(locale)}/about/contact`} label={c.contact}/></div></nav>
</article>}
function InfoCard({label,value}:{label:string;value:string}){return <div className="rounded-lg border bg-surface p-5"><p className="text-sm font-semibold uppercase tracking-[0.1em] text-muted-foreground">{label}</p><p className="mt-2 whitespace-pre-line font-serif text-2xl leading-8">{value}</p></div>}
function Fact({term,value}:{term:string;value:string}){return <div><dt className="text-sm font-semibold text-muted-foreground">{term}</dt><dd className="mt-1 text-lg">{value}</dd></div>}
function LinkButton({href,label}:{href:string;label:string}){return <Link href={href as Route} className="inline-flex min-h-11 items-center rounded-md border px-4 font-medium hover:bg-muted">{label}</Link>}
function ExternalButton({href,label}:{href:string;label:string}){return <Link href={href} target="_blank" rel="noreferrer" className="inline-flex min-h-11 items-center rounded-md border px-4 font-medium hover:bg-muted">{label}<span aria-hidden="true" className="ml-2">↗</span></Link>}
function ExternalCard({title,detail,href,action}:{title:string;detail:string;href:string;action:string}){return <article className="flex h-full flex-col rounded-lg border bg-surface p-5 shadow-[var(--shadow-soft)]"><h3 className="font-serif text-2xl">{title}</h3><p className="mt-2 break-words text-sm text-muted-foreground">{detail}</p><div className="mt-6"><ExternalButton href={href} label={action}/></div></article>}
