"use client";
import {useId,useState} from "react";
import type {ContentLanguage} from "@/types/content";

type Section="mentoring"|"prayer-support"|"growth-groups"|"contact"|"testimonies";
const TOGETHER_ENDPOINT="https://paulzhang-together.paulzhang901.workers.dev/";
const fieldClass="min-h-11 w-full rounded-md border bg-surface px-3 py-2 text-foreground outline-none focus-visible:ring-2 focus-visible:ring-primary";
const copy={
 "zh-CN":{name:"姓名",email:"电子邮箱",phone:"电话（选填）",contact:"希望联系方式",emailChoice:"电子邮箱",phoneChoice:"电话",wechat:"微信",message:"内容",submit:"提交",submitting:"正在提交…",success:"已经成功提交。Paul 会按照你选择的方式跟进。",failure:"提交没有送达，请稍后重试。",language:"希望使用的语言",help:"你希望得到哪方面的帮助？（选填）",availability:"一般方便的时间（选填）",mode:"参加方式",online:"线上",inPerson:"线下",either:"都可以",subject:"主题",title:"见证标题",prayerTeam:"可以与祷告团队分享",publicPrayer:"可以公开分享（默认不勾选）",followUp:"可以联系我进一步了解",publish:"允许将见证公开发表（默认不勾选）",privacy:"你的提交会直接发送给 Paul，不会自动发布，也不会作为网站内容保存。"},
 "en-US":{name:"Name",email:"Email",phone:"Phone (optional)",contact:"Preferred contact method",emailChoice:"Email",phoneChoice:"Phone",wechat:"WeChat",message:"Message",submit:"Submit",submitting:"Submitting…",success:"Your submission was delivered successfully. Paul can follow up using your preferred method.",failure:"Your submission was not delivered. Please try again later.",language:"Preferred language",help:"What would you like help with? (optional)",availability:"General availability (optional)",mode:"Meeting preference",online:"Online",inPerson:"In person",either:"Either",subject:"Subject",title:"Testimony title",prayerTeam:"May be shared with the prayer team",publicPrayer:"May be shared publicly (off by default)",followUp:"You may contact me for follow-up",publish:"Permission to publish this testimony (off by default)",privacy:"Your submission is delivered privately to Paul. It is not automatically published or stored as website content."}
} as const;

export function TogetherSubmissionForm({locale,section}:{locale:ContentLanguage;section:Section}){
 const c=copy[locale],id=useId(); const [state,setState]=useState<"idle"|"submitting"|"success"|"failure">("idle"); const [error,setError]=useState("");
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError("");setState("submitting");const form=e.currentTarget,fd=new FormData(form);const subject=section==="contact"?String(fd.get("subject")||""):section==="testimonies"?String(fd.get("testimonyTitle")||""):c[section==="mentoring"?"help":section==="prayer-support"?"message":section==="growth-groups"?"mode":"message"];const details:string[]=[];
 if(section==="mentoring"){details.push(`Preferred contact: ${String(fd.get("preferredContactMethod")||"")}`,`Preferred language: ${String(fd.get("preferredLanguage")||"")}`,`Help requested: ${String(fd.get("helpWith")||"")}`)}
 if(section==="prayer-support"){details.push(`Preferred contact: ${String(fd.get("preferredContactMethod")||"")}`,`Share with prayer team: ${fd.get("sharePrayerTeam")==="on"?"YES":"NO"}`,`Share publicly: ${fd.get("sharePublicly")==="on"?"YES":"NO"}`)}
 if(section==="growth-groups"){details.push(`Preferred contact: ${String(fd.get("preferredContactMethod")||"")}`,`Preferred language: ${String(fd.get("preferredLanguage")||"")}`,`Availability: ${String(fd.get("availability")||"")}`,`Meeting mode: ${String(fd.get("meetingMode")||"")}`)}
 if(section==="contact")details.push(`Preferred contact: ${String(fd.get("preferredContactMethod")||"")}`);
 if(section==="testimonies")details.push(`Preferred contact: ${String(fd.get("preferredContactMethod")||"")}`,`May contact for follow-up: ${fd.get("followUpPermission")==="on"?"YES":"NO"}`,`Permission to publish: ${fd.get("publishPermission")==="on"?"YES":"NO"}`);
 const payload={name:String(fd.get("name")||""),email:String(fd.get("email")||""),phone:String(fd.get("phone")||""),subject,message:[...details,"",String(fd.get("message")||"")].join("\n"),language:locale,page:`${window.location.pathname}#${section}`};
 try{const r=await fetch(TOGETHER_ENDPOINT,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});if(!r.ok)throw new Error();form.reset();setState("success")}catch{setError(c.failure);setState("failure")}}
 return <form onSubmit={submit} className="space-y-5"><p className="text-sm leading-6 text-muted-foreground">{c.privacy}</p><Field label={c.name} id={`${id}-name`}><input id={`${id}-name`} name="name" required maxLength={100} autoComplete="name" className={fieldClass}/></Field><Field label={c.email} id={`${id}-email`}><input id={`${id}-email`} name="email" type="email" required maxLength={254} autoComplete="email" className={fieldClass}/></Field><Field label={c.phone} id={`${id}-phone`}><input id={`${id}-phone`} name="phone" type="tel" maxLength={40} autoComplete="tel" className={fieldClass}/></Field><Field label={c.contact} id={`${id}-contact`}><select id={`${id}-contact`} name="preferredContactMethod" required className={fieldClass}><option value="email">{c.emailChoice}</option><option value="phone">{c.phoneChoice}</option><option value="wechat">{c.wechat}</option></select></Field>
 {section==="mentoring"&&<><Field label={c.language} id={`${id}-lang`}><input id={`${id}-lang`} name="preferredLanguage" maxLength={40} className={fieldClass}/></Field><Field label={c.help} id={`${id}-help`}><input id={`${id}-help`} name="helpWith" maxLength={300} className={fieldClass}/></Field></>}
 {section==="growth-groups"&&<><Field label={c.language} id={`${id}-lang`}><input id={`${id}-lang`} name="preferredLanguage" maxLength={40} className={fieldClass}/></Field><Field label={c.availability} id={`${id}-availability`}><input id={`${id}-availability`} name="availability" maxLength={300} className={fieldClass}/></Field><Field label={c.mode} id={`${id}-mode`}><select id={`${id}-mode`} name="meetingMode" className={fieldClass}><option value="either">{c.either}</option><option value="online">{c.online}</option><option value="in-person">{c.inPerson}</option></select></Field></>}
 {section==="contact"&&<Field label={c.subject} id={`${id}-subject`}><input id={`${id}-subject`} name="subject" required maxLength={160} className={fieldClass}/></Field>}{section==="testimonies"&&<Field label={c.title} id={`${id}-title`}><input id={`${id}-title`} name="testimonyTitle" required maxLength={160} className={fieldClass}/></Field>}
 <Field label={c.message} id={`${id}-message`}><textarea id={`${id}-message`} name="message" required maxLength={6000} rows={7} className={fieldClass}/></Field>
 {section==="prayer-support"&&<div className="space-y-3"><Check name="sharePrayerTeam" label={c.prayerTeam}/><Check name="sharePublicly" label={c.publicPrayer}/></div>}{section==="testimonies"&&<div className="space-y-3"><Check name="followUpPermission" label={c.followUp}/><Check name="publishPermission" label={c.publish}/></div>}
 <button type="submit" disabled={state==="submitting"} className="inline-flex min-h-11 items-center rounded-md bg-primary px-5 font-medium text-primary-foreground disabled:opacity-60">{state==="submitting"?c.submitting:c.submit}</button><div aria-live="polite" className="text-sm">{state==="success"?<p>{c.success}</p>:error?<p role="alert">{error}</p>:null}</div></form>;
}

function Field({label,id,children}:{label:string;id:string;children:React.ReactNode}){return <div><label htmlFor={id} className="mb-2 block font-medium">{label}</label>{children}</div>}
function Check({name,label}:{name:string;label:string}){return <label className="flex items-start gap-3"><input type="checkbox" name={name} className="mt-1 size-4"/><span>{label}</span></label>}
