"use client";
import Script from "next/script";
import {useEffect,useId,useState} from "react";
import type {ContentLanguage} from "@/types/content";

type Section="mentoring"|"prayer-support"|"growth-groups"|"contact"|"testimonies";
type TurnstileWindow=Window & {turnstile?:{reset:()=>void}};
const fieldClass="min-h-11 w-full rounded-md border bg-surface px-3 py-2 text-foreground outline-none focus-visible:ring-2 focus-visible:ring-primary";
const copy={
 "zh-CN":{name:"姓名",email:"电子邮箱",phone:"电话（选填）",contact:"希望联系方式",emailChoice:"电子邮箱",phoneChoice:"电话",wechat:"微信",message:"内容",submit:"提交",submitting:"正在提交…",success:"已经成功提交。Paul 会按照你选择的方式跟进。",failure:"提交没有送达，请稍后重试。",unavailable:"在线提交目前尚未启用，请稍后再试。",verify:"请完成人机验证。",language:"希望使用的语言",help:"你希望得到哪方面的帮助？（选填）",availability:"一般方便的时间（选填）",mode:"参加方式",online:"线上",inPerson:"线下",either:"都可以",subject:"主题",title:"见证标题",prayerTeam:"可以与祷告团队分享",publicPrayer:"可以公开分享（默认不勾选）",followUp:"可以联系我进一步了解",publish:"允许将见证公开发表（默认不勾选）",privacy:"你的提交会直接发送给 Paul，不会自动发布，也不会作为网站内容保存。"},
 "en-US":{name:"Name",email:"Email",phone:"Phone (optional)",contact:"Preferred contact method",emailChoice:"Email",phoneChoice:"Phone",wechat:"WeChat",message:"Message",submit:"Submit",submitting:"Submitting…",success:"Your submission was delivered successfully. Paul can follow up using your preferred method.",failure:"Your submission was not delivered. Please try again later.",unavailable:"Online submission is not configured yet. Please try again later.",verify:"Please complete the human verification.",language:"Preferred language",help:"What would you like help with? (optional)",availability:"General availability (optional)",mode:"Meeting preference",online:"Online",inPerson:"In person",either:"Either",subject:"Subject",title:"Testimony title",prayerTeam:"May be shared with the prayer team",publicPrayer:"May be shared publicly (off by default)",followUp:"You may contact me for follow-up",publish:"Permission to publish this testimony (off by default)",privacy:"Your submission is delivered privately to Paul. It is not automatically published or stored as website content."}
} as const;

export function TogetherSubmissionForm({locale,section}:{locale:ContentLanguage;section:Section}){
 const c=copy[locale],id=useId(); const [siteKey,setSiteKey]=useState<string|null>(null); const [ready,setReady]=useState<boolean|null>(null); const [state,setState]=useState<"idle"|"submitting"|"success"|"failure">("idle"); const [error,setError]=useState("");
 useEffect(()=>{let active=true;fetch("/api/together",{headers:{Accept:"application/json"}}).then(async r=>{if(!r.ok)throw new Error();const x=await r.json();if(active){setSiteKey(typeof x.turnstileSiteKey==="string"?x.turnstileSiteKey:null);setReady(x.ready===true);}}).catch(()=>{if(active)setReady(false)});return()=>{active=false}},[]);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError("");setState("submitting");const form=e.currentTarget,fd=new FormData(form);const token=String(fd.get("cf-turnstile-response")||"");if(!token){setError(c.verify);setState("failure");return}const payload:ObjectRecord={section,locale,name:String(fd.get("name")||""),email:String(fd.get("email")||""),phone:String(fd.get("phone")||""),preferredContactMethod:String(fd.get("preferredContactMethod")||""),message:String(fd.get("message")||""),turnstileToken:token};
 if(section==="mentoring"){payload.preferredLanguage=String(fd.get("preferredLanguage")||"");payload.helpWith=String(fd.get("helpWith")||"")}
 if(section==="prayer-support"){payload.sharePrayerTeam=fd.get("sharePrayerTeam")==="on";payload.sharePublicly=fd.get("sharePublicly")==="on"}
 if(section==="growth-groups"){payload.preferredLanguage=String(fd.get("preferredLanguage")||"");payload.availability=String(fd.get("availability")||"");payload.meetingMode=String(fd.get("meetingMode")||"")}
 if(section==="contact")payload.subject=String(fd.get("subject")||"");if(section==="testimonies"){payload.testimonyTitle=String(fd.get("testimonyTitle")||"");payload.followUpPermission=fd.get("followUpPermission")==="on";payload.publishPermission=fd.get("publishPermission")==="on"}
 try{const r=await fetch("/api/together",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const x=await r.json().catch(()=>({}));if(!r.ok||x.ok!==true)throw new Error();form.reset();(window as TurnstileWindow).turnstile?.reset();setState("success")}catch{(window as TurnstileWindow).turnstile?.reset();setError(c.failure);setState("failure")}}
 if(ready===null)return <p className="rounded-md border p-4 text-sm text-muted-foreground" aria-live="polite">…</p>;
 if(!ready||!siteKey)return <p className="rounded-md border p-4 text-sm text-muted-foreground" role="status">{c.unavailable}</p>;
 return <form onSubmit={submit} className="space-y-5" noValidate={false}><Script src="https://challenges.cloudflare.com/turnstile/v0/api.js" strategy="afterInteractive"/><p className="text-sm leading-6 text-muted-foreground">{c.privacy}</p><Field label={c.name} id={`${id}-name`}><input id={`${id}-name`} name="name" required maxLength={100} autoComplete="name" className={fieldClass}/></Field><Field label={c.email} id={`${id}-email`}><input id={`${id}-email`} name="email" type="email" required maxLength={254} autoComplete="email" className={fieldClass}/></Field><Field label={c.phone} id={`${id}-phone`}><input id={`${id}-phone`} name="phone" type="tel" maxLength={40} autoComplete="tel" className={fieldClass}/></Field><Field label={c.contact} id={`${id}-contact`}><select id={`${id}-contact`} name="preferredContactMethod" required className={fieldClass}><option value="email">{c.emailChoice}</option><option value="phone">{c.phoneChoice}</option><option value="wechat">{c.wechat}</option></select></Field>
 {section==="mentoring"&&<><Field label={c.language} id={`${id}-lang`}><input id={`${id}-lang`} name="preferredLanguage" maxLength={40} className={fieldClass}/></Field><Field label={c.help} id={`${id}-help`}><input id={`${id}-help`} name="helpWith" maxLength={300} className={fieldClass}/></Field></>}
 {section==="growth-groups"&&<><Field label={c.language} id={`${id}-lang`}><input id={`${id}-lang`} name="preferredLanguage" maxLength={40} className={fieldClass}/></Field><Field label={c.availability} id={`${id}-availability`}><input id={`${id}-availability`} name="availability" maxLength={300} className={fieldClass}/></Field><Field label={c.mode} id={`${id}-mode`}><select id={`${id}-mode`} name="meetingMode" className={fieldClass}><option value="either">{c.either}</option><option value="online">{c.online}</option><option value="in-person">{c.inPerson}</option></select></Field></>}
 {section==="contact"&&<Field label={c.subject} id={`${id}-subject`}><input id={`${id}-subject`} name="subject" required maxLength={160} className={fieldClass}/></Field>}{section==="testimonies"&&<Field label={c.title} id={`${id}-title`}><input id={`${id}-title`} name="testimonyTitle" required maxLength={160} className={fieldClass}/></Field>}
 <Field label={c.message} id={`${id}-message`}><textarea id={`${id}-message`} name="message" required maxLength={6000} rows={7} className={fieldClass}/></Field>
 {section==="prayer-support"&&<div className="space-y-3"><Check name="sharePrayerTeam" label={c.prayerTeam}/><Check name="sharePublicly" label={c.publicPrayer}/></div>}{section==="testimonies"&&<div className="space-y-3"><Check name="followUpPermission" label={c.followUp}/><Check name="publishPermission" label={c.publish}/></div>}
 <div className="cf-turnstile" data-sitekey={siteKey} data-theme="auto" data-size="flexible"/><button type="submit" disabled={state==="submitting"} className="inline-flex min-h-11 items-center rounded-md bg-primary px-5 font-medium text-primary-foreground disabled:opacity-60">{state==="submitting"?c.submitting:c.submit}</button><div aria-live="polite" className="text-sm">{state==="success"?<p>{c.success}</p>:error?<p role="alert">{error}</p>:null}</div></form>;
}
type ObjectRecord=Record<string,string|boolean>;
function Field({label,id,children}:{label:string;id:string;children:React.ReactNode}){return <div><label htmlFor={id} className="mb-2 block font-medium">{label}</label>{children}</div>}
function Check({name,label}:{name:string;label:string}){return <label className="flex items-start gap-3"><input type="checkbox" name={name} className="mt-1 size-4"/><span>{label}</span></label>}
